### ISSUE TITLE
_kgflags_flag_t initialized with garbage.

### ISSUE THREAD

**Issue by skinpop** [kgabis/kgflags#1]
This behavior probably depends on compiler settings(I'm using VS C++ 2017) . Anyway, I was having a bizarre issue where if I used more than seven flags then all of them would have the error field initialized to '8', which meant failing to supply required flags didn't generate the KGFLAGS_ERROR_KIND_UNASSIGNED_FLAG error. 

I simply changed
```
_kgflags_flag_t flag; 
```
to
```
_kgflags_flag_t flag = {};
```
in all the relevant places, which fixed the issue for me.

**Comment by kgabis** [comment]
I had to use memset to make it compatible with both C and C++.
